apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: nginx
spec:
  generators:
    - list:
        elements:
          - chartName: nginx
            namespace: argocd-demo
          - chartName: nginx2
            namespace: argocd-demo
          # This one should not deploy properly
          # - chartName: nginx
          #   namespace: argocd-demo2
  template:
    metadata:
      name: "{{chartName}}"
    spec:
      project: argocd-demo
      source:
        repoURL: https://github.com/jake-dhcs/sample-helm-charts.git
        targetRevision: HEAD
        path: charts/nginx
      destination:
        server: https://kubernetes.default.svc
        namespace: {{namespace}}
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - PruneLast=true
          - Validate=true
        retry:
          limit: 5 # number of failed sync attempt retries; unlimited number of attempts if less than 0
          backoff:
            duration: 5s # the amount to back off. Default unit is seconds, but could also be a duration (e.g. "2m", "1h")
            factor: 2 # a factor to multiply the base duration after each failed retry
            maxDuration: 3m # the maximum amount of time allowed for the backoff strategy
