apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: nginx
spec:
  generators:
    - list:
        elements:
          - chartName: nginx
            namespace: argocd-demo
          - chartName: nginx2
            namespace: argocd-demo
          # This one should not deploy properly
          - chartName: nginx
            namespace: argocd-demo2
  template:
    metadata:
      name: "{{chartName}}"
    spec:
      project: argocd-demo
      source:
        repoURL: https://github.com/jake-dhcs/sample-helm-charts
        targetRevision: HEAD
        path: {{chartName}}
      destination:
        server: https://kubernetes.default.svc
        namespace: {{namespace}}
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - PruneLast=true
          - Validate=true