apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-application
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  source:
    repoURL: https://github.com/jake-dhcs/sample-eks-with-argo
    targetRevision: HEAD
    path: applications
  destination:
    namespace: argo-demo
    name: root-application
  project: argocd-demo
  syncPolicy:
    automated: {}
    syncOptions:
      - PruneLast=true
      - CreateNamespace=true
